#!/usr/bin/env bash
# apply-ics-dhcp.sh -- Detect the primary wired NIC and write a persistent
# netplan config requesting DHCPv4 (for Windows ICS on 192.168.137.0/24).
#
# Run as root on an Ubuntu node connected to the ICS switch:
#   sudo bash apply-ics-dhcp.sh
#   sudo bash apply-ics-dhcp.sh enp0s31f6   # override NIC name
set -euo pipefail

NETPLAN_FILE="/etc/netplan/99-ics-dhcp.yaml"

detect_nic() {
  # Prefer the first non-virtual, non-wireless, non-loopback NIC that is UP or
  # has carrier. Walks /sys/class/net/ to avoid requiring `ip -j`.
  for dev in /sys/class/net/*; do
    name=$(basename "$dev")
    [ "$name" = "lo" ] && continue
    # Skip wireless
    [ -d "$dev/wireless" ] && continue
    # Skip virtual (bridges, veth, docker, etc.)
    if readlink -f "$dev" 2>/dev/null | grep -q '/virtual/'; then
      continue
    fi
    # Must have carrier or at least be UP
    local operstate
    operstate=$(cat "$dev/operstate" 2>/dev/null || echo "unknown")
    if [ "$operstate" = "up" ] || [ "$operstate" = "unknown" ]; then
      echo "$name"
      return 0
    fi
  done
  return 1
}

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: Run as root (sudo)." >&2
  exit 1
fi

NIC="${1:-}"
if [ -z "$NIC" ]; then
  NIC=$(detect_nic) || {
    echo "ERROR: Could not auto-detect a wired Ethernet NIC." >&2
    echo "       List interfaces with: ip -br link" >&2
    echo "       Then re-run: sudo bash $0 <interface>" >&2
    exit 1
  }
  echo "Auto-detected NIC: $NIC"
fi

# Sanity: does the interface exist?
if [ ! -d "/sys/class/net/$NIC" ]; then
  echo "ERROR: Interface $NIC does not exist. Check with: ip -br link" >&2
  exit 1
fi

echo "Writing $NETPLAN_FILE for $NIC (dhcp4: true) ..."

cat > "$NETPLAN_FILE" <<EOF
# Generated by telvm apply-ics-dhcp.sh -- persistent ICS DHCPv4.
network:
  version: 2
  ethernets:
    $NIC:
      dhcp4: true
      dhcp6: false
EOF

chmod 600 "$NETPLAN_FILE"
echo "Applying netplan ..."
netplan apply

sleep 3
echo ""
echo "Current IPv4 on $NIC:"
ip -4 addr show dev "$NIC" 2>/dev/null || echo "(no address yet -- wait a few seconds and check again)"
echo ""
echo "Done. If 192.168.137.x appeared, ICS DHCP is working and will persist across reboots."
